server:
  port: 8080
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.example.parrot.mybatis.entity
  configuration:
    map-underscore-to-camel-case: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oj
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

knife4j:
  enable: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

